@baseUrl = http://localhost:8080

GET {{baseUrl}}/categories
###
GET {{baseUrl}}/categories/page?size=2&page=1

###
GET  {{baseUrl}}/categories/4
###
GET {{baseUrl}}/categories/description/Mo%

###
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "description": "Teste"
}

###
PUT {{baseUrl}}/categories/4
Content-Type: application/json

{
    "description": "Lanches"
}

###
DELETE {{baseUrl}}/categories/6

### Product
GET {{baseUrl}}/products
###
GET {{baseUrl}}/products/page?size=2&page=7
###
GET  {{baseUrl}}/products/1
###
GET {{baseUrl}}/products/description/%especial%
###
POST {{baseUrl}}/products
Content-Type: application/json

{
    "code": "0017",
    "description": "Pizza Grande",
    "price": 33.00,
    "quantity": 0.00,
    "categoryId": 1
}
###
PUT {{baseUrl}}/products/1
Content-Type: application/json

{
  "id": 1,
  "code": "0002",
  "barcode": "",
  "description": "Regrigerante Lata",
  "price": 5.00,
  "quantity": 0.00,
  "categoryId": 4
}

###
DELETE {{baseUrl}}/products/1

### Client
GET {{baseUrl}}/customers
###
GET {{baseUrl}}/customers/page?size=2&page=1
###
GET {{baseUrl}}/customers/4
###
GET {{baseUrl}}/customers/name/%allana%
###
POST {{baseUrl}}/customers
Content-Type: application/json

{
    "cpf": "78447421734",
    "name": "Allana Rosa",
    "cep": "32215153",
    "street": "Rua Sapucaia",
    "number": "323",
    "neighborhood": "Jardim Industrial",
    "blocked": true,
    "creditLimit": 1000.00
}

###
POST {{baseUrl}}/customers
Content-Type: application/json

{
    "cpf": "78447421734",
    "cep": "32215153",
    "street": "Rua Sapucaia",
    "number": "323",
    "neighborhood": "Jardim Industrial",
    "blocked": true,
    "creditLimit": -1.00
}

###
PUT {{baseUrl}}/customers/8
Content-Type: application/json

{
    "cpf": "78447421734",
    
    "cep": "32215153",
    "street": "Rua Sapucaia",
    "number": "324",
    "neighborhood": "Jardim Industrial",
    "blocked": true,
    "creditLimit": -1000.00
}
###
PUT {{baseUrl}}/customers/7
Content-Type: application/json

{
    "cpf": "78807425734",
    "name": "Allana Rosa Silva",
    "cep": "32215153",
    "street": "Rua Sapucaia",
    "number": "324",
    "neighborhood": "Jardim Industrial",
    "blocked": true,
    "creditLimit": 1000.00
}

###
DELETE {{baseUrl}}/customers/7