@baseUrl = http://localhost:8080

GET {{baseUrl}}/categories
###
GET {{baseUrl}}/categories/page?size=2&page=1

###
GET  {{baseUrl}}/categories/4
###
GET {{baseUrl}}/categories/description/Mo%

###
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "description": "Teste"
}

###
PUT {{baseUrl}}/categories/4
Content-Type: application/json

{
    "description": "Lanches"
}

###
DELETE {{baseUrl}}/categories/4