CREATE TABLE CATEGORY (
	ID INT AUTO_INCREMENT, 
	DESCRIPTION VARCHAR(80) NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME,
	PRIMARY KEY(ID)
);

INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Pizzas', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Lanches', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Pratos', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Bebidas', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Sobremesas', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Salgados', CURRENT_TIMESTAMP());

CREATE TABLE PRODUCT (
	ID INT AUTO_INCREMENT, 
	CODE VARCHAR(4) NOT NULL UNIQUE,
	BARCODE VARCHAR(32) DEFAULT '',
	DESCRIPTION VARCHAR(80) NOT NULL,
	PRICE DECIMAL(7, 2) NOT NULL,
	QUANTITY DECIMAL(7, 2) DEFAULT 0,
	CATEGORY_ID INT NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME,
	PRIMARY KEY(ID),
	FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY (ID)
);

INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0001', 'Regrigerante Lata', 4.00, 4, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0002', 'Regrigerante 1L', 7.00, 4, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0003', 'Água Mineral', 2.00, 4, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0004', 'Pizza Pequena', 22.00, 1, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0005', 'Pizza Média', 27.00, 1, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0006', 'Torrada', 3.00, 2, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0007', 'X-Salada', 5.00, 2, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0008', 'Especial', 12.00, 2, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0009', 'Hambúrger', 5.00, 2, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0010', 'Yakissoba', 32.00, 3, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0011', 'Yakissoba Especial', 35.00, 3, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0012', 'Risoto', 32.00, 3, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0013', 'Crepe de Carne', 20.00, 3, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0014', 'Café Expresso', 2.50, 5, CURRENT_TIMESTAMP());
INSERT INTO PRODUCT (CODE, DESCRIPTION, PRICE, CATEGORY_ID, CREATED_AT) VALUES ('0015', 'Chocolate Quente', 6.00, 5, CURRENT_TIMESTAMP());

CREATE TABLE CUSTOMER (
	ID INT AUTO_INCREMENT,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	NAME VARCHAR(80) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	STREET VARCHAR(80) DEFAULT '',
	NUMBER VARCHAR(6) DEFAULT '',
	NEIGHBORHOOD VARCHAR(80) DEFAULT '',
	IS_BLOCKED BOOLEAN,
	CREDIT_LIMIT DECIMAL(7, 2) DEFAULT 0.00,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME,
	
	PRIMARY KEY(ID)
);

INSERT INTO CUSTOMER (CPF, NAME, CEP, STREET, NUMBER, NEIGHBORHOOD, IS_BLOCKED, CREDIT_LIMIT, CREATED_AT) VALUES ('51120550572', 'Luiza da Cruz', '', '', '', '', FALSE, 0.00, CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER (CPF, NAME, CEP, STREET, NUMBER, NEIGHBORHOOD, IS_BLOCKED, CREDIT_LIMIT, CREATED_AT) VALUES ('20218626827', 'Noah Vieira', '', '', '', '', FALSE, 1000.00, CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER (CPF, NAME, CEP, STREET, NUMBER, NEIGHBORHOOD, IS_BLOCKED, CREDIT_LIMIT, CREATED_AT) VALUES ('49907477206', 'Isadora Duarte', '', '', '', '', TRUE, 0.00, CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER (CPF, NAME, CEP, STREET, NUMBER, NEIGHBORHOOD, IS_BLOCKED, CREDIT_LIMIT, CREATED_AT) VALUES ('78807425734', 'Allana Rosa', '32215153', 'Rua Sapucaia', '323', 'Jardim Industrial', FALSE, 0.00, CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER (CPF, NAME, CEP, STREET, NUMBER, NEIGHBORHOOD, IS_BLOCKED, CREDIT_LIMIT, CREATED_AT) VALUES ('43698905272', 'Bianca Jesus', '', '', '', '', FALSE, 0.00, CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER (CPF, NAME, CEP, STREET, NUMBER, NEIGHBORHOOD, IS_BLOCKED, CREDIT_LIMIT, CREATED_AT) VALUES ('29407317994', 'Cláudio Dias', '', '', '', '', FALSE, 0.00, CURRENT_TIMESTAMP());