CREATE TABLE CATEGORY (
	ID INT AUTO_INCREMENT, 
	DESCRIPTION VARCHAR(80) NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME,
	PRIMARY KEY(ID)
);

INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Pizza', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Lanches', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Pratos', CURRENT_TIMESTAMP());